language: python

branches:
  only:
  - master

services:
- docker

before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t onestoop/pypytest .
  - docker push onestoop/pypytest

deploy:
  provider: script
  script: bash scripts/docker_push
  on:
    branch: master

