language: bash

sudo: required

branches:
  only:
  - master

services:
- docker

before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt` && sudo mv kubectl /usr/local/bin/kubectl
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t onestoop/pypytest:$TRAVIS_BUILD_NUMBER .
  - docker push onestoop/pypytest

script:
- bash scripts/updateKube.sh
- bash scripts/docker_push

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

