apiVersion: apps/v1
kind: Deployment
metadata:
  name: pypytest
  namespace: default
  labels:
    app: pypytest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pypytest
  template:
    metadata:
      labels:
        app: pypytest
    spec:
      containers:
        - name: pypytest
          image: onestoop/pypytest:VERSION
          ports:
            - containerPort: 80
              name: http

