apiVersion: v1
kind: Service
metadata:
  name: pypytest
  namespace: default
  labels:
    app: pypytest
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: pypytest
